### ISSUE TITLE
Approving a PR for a code review does not count as participation in a PR

### ISSUE THREAD

**Issue by brandongk-ubco** [brandongk-ubco/gitstats#97]
Comment added by @merelister in #89:

@brandongk-ubco We've noticed that approving a PR for a code review does not count as participation in a PR according to gitstats - would it perhaps be possible to use this feature to decide whether to count LoC? For example, if a PR is not approved then it is not counted, whether it is merged or not.

**Comment by brandongk-ubco** [comment]
@merelister - I moved this comment here as the other issue had been closed.

Approving a PR should certainly count as activity on a PR.  The stats collection looks at review comments (reviews without a single comment are not very valuable).  Are the reviews you are referring to accompanied by a comment?  Even a trivial LGTM should count, though more in-depth commenting is generally preferred.

**Comment by brandongk-ubco** [comment]
As for approval of PRs, a non-approved PR should not be merged, and an approved PR should always be merged.  I'm not 100% following what the suggestion is here, but it sounds to me like the proposal is replacing merged/unmerged with approved/not approved when considering PRs, is that correct?

**Comment by merelister** [comment]
@brandongk-ubco unless it's been changed in the last two weeks, we've noticed that when you review a PR and choose the "approve and comment" option, the comment is not counted. Comments that are separate from an approval are counted.

The  suggestion was that a non-approved PR would not count toward LoC as a way of allowing groups to filter out large contributions that would unbalance individual effort scores, but I realize this would lead to bad practices with GitHub and also is less necessary with the changes you've made in the newest version with counting LoC.

**Comment by brandongk-ubco** [comment]
@merelister - OK, I will do some testing on the "approve and comment" option and confirm.  If it is working as you describe, then it's a bug and must be fixed.  Thanks for clarifying!

If we want to start doing something different with PRs based on logic, I believe it's better to be explicit rather than making assumptions.  I would propose adding a label to the PR along the lines of "prototype" or some such which we could look for.  I am hesitant to do it, since such options will probably not be immediately obvious to future users, but if it helps solve some edge cases, maybe it's worth it.  This would need to be discussed with @bohuie as well, since it's a feature addition.

**Comment by brandongk-ubco** [comment]
@merelister - You are correct, this is a bug.  I released https://github.com/brandongk-ubco/gitstats/releases/tag/v1.0.7 with the fix from PR #98.  With the fix, I now see the two comments which were previously missing:

`0  Brandon Graham-Knight   98        1         72         22       94         2         True`

**Comment by brandongk-ubco** [comment]
@merelister - Can you please confirm that this is now working with the new version for you, and close this issue if you believe it's resolved?

**Comment by merelister** [comment]
We're still having issues unfortunately. We tried with [this pull request ](https://github.com/stillwwater/healthcircles/pull/65) - I approved the PR and added a comment with my review, but my comment has not been counted.

**Comment by brandongk-ubco** [comment]
Did you make sure you had upgraded to v1.0.7 before running?

**Comment by mjcrouse** [comment]
Sorry, yes I think this is working as intended. I had uninstalled 1.0.4 and installed 1.0.7 but script was still running 1.0.4 somehow.

**Comment by brandongk-ubco** [comment]
Fair enough, glad it's sorted.  I am adding a version check in #104 to help prevent old versions... I am closing this issue as I believe it's resolved.  Thanks again for the feedback!
